version: "3.8"

services:
  # Aplicación cliente
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - incidents-network
    depends_on:
      - api
    environment:
      - API_URL=http://api:3000

  # API de incidentes
  api:
    image: node:20-alpine
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "npm install && bun index.ts"
    ports:
      - "3000:3000"
    networks:
      - incidents-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=incidents_db

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=incidents_db
    ports:
      - "5432:5432"
    networks:
      - incidents-network

networks:
  incidents-network:
    driver: bridge

volumes:
  postgres_data:
